abs-path			:= drivers/sensors

src-$(CONFIG_ANALOG_SENSORS)	+= $(abs-path)/analog_sensor.c
src-$(CONFIG_GP2D120)		+= $(abs-path)/gp2d120.c
src-$(CONFIG_GP2Y0A21)		+= $(abs-path)/gp2y0a21.c
src-$(CONFIG_GP2Y0A41)		+= $(abs-path)/gp2y0a41.c
