abs-path		:= core

src-y			+= $(abs-path)/avoidance.c
src-y			+= $(abs-path)/controller.c
src-y			+= $(abs-path)/encoder.c
src-y			+= $(abs-path)/main.c
src-y			+= $(abs-path)/msched.c
src-y			+= $(abs-path)/odometry.c
src-y			+= $(abs-path)/pid.c
