abs-path		:= arch/xmega/mach-geonobot

src-y			+= $(abs-path)/action.c
src-y			+= $(abs-path)/platform.c
src-y			+= $(abs-path)/platform_task.c
src-y			+= $(abs-path)/route.c
src-y			+= $(abs-path)/sensor.c
